/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.wf.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.draw.figures.LineConnector;
import com.rameses.rcp.ui.annotations.Template;
/**
 *
 * @author Elmo Nazareno
 */
@Template(FormPage.class)
public class WorkflowGUIPage extends javax.swing.JPanel {

    /**
     * Creates new form WokflowDrawPage
     */
    public WorkflowGUIPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawComponent2 = new com.rameses.rcp.draw.components.DrawComponent();

        setLayout(new java.awt.BorderLayout());

        drawComponent2.setHandler("handler");
        add(drawComponent2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.draw.components.DrawComponent drawComponent2;
    // End of variables declaration//GEN-END:variables
}
